// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bakery-variants/DarkLuxe.tsx": () => import("../components/mockups/bakery-variants/DarkLuxe.tsx"),
  "./components/mockups/bakery-variants/RusticGarden.tsx": () => import("../components/mockups/bakery-variants/RusticGarden.tsx"),
  "./components/mockups/bakery-variants/SweetShop.tsx": () => import("../components/mockups/bakery-variants/SweetShop.tsx")
};
